In [1]:
import numpy as np
import tensorflow as tf
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder as oneHot
from MLP import MLP
from genetic_optimisation import genetic_optimisation as GO

mnist = tf.keras.datasets.mnist
(x_train, y_train),(x_test, y_test) = mnist.load_data()

W0802 16:51:43.719056 4623492544 deprecation_wrapper.py:119] From /Users/jahanpd/Documents/ML/algorithms/MLP.py:5: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.



In [2]:
x_train, x_test = x_train.reshape(60000,28*28) / 255.0, x_test.reshape(10000,28*28) / 255.0
y_train = y_train.reshape(len(y_train),1)
y_test = y_test.reshape(len(y_test),1)
onehot = oneHot()
onehot.fit(y_train)
y_train = onehot.transform(y_train).toarray()
y_test = onehot.transform(y_test).toarray()

/Users/jahanpd/miniconda3/envs/ml/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [3]:
mlp = MLP(x_train,y_train)
mlp.build(1,10)

True
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 784)]             0         
_________________________________________________________________
dense (Dense)                (None, 10)                7850      
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dropout (Dropout)            (None, 10)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                110       
Total params: 8,070
Trainable params: 8,070
Non-trainable params: 0
_________________________________________________________________


In [4]:
mlp.train(1)

W0802 16:51:44.943835 4623492544 deprecation.py:323] From /Users/jahanpd/miniconda3/envs/ml/lib/python3.7/site-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Train on 54000 samples, validate on 6000 samples
54000/54000 [==============================] - 4s 71us/sample - loss: 1.0791 - categorical_accuracy: 0.6184 - val_loss: 0.4379 - val_categorical_accuracy: 0.8855


In [5]:
mlp.evaluate(x_test,y_test)

10000/10000 [==============================] - 0s 27us/sample - loss: 0.4799 - categorical_accuracy: 0.8680


0.868

In [10]:
layers = [1,10]
nodes = [2,100]
go = GO(model=MLP, 
        x_train=x_train, y_train=y_train, x_test=x_test, y_test=y_test, 
        param_one=layers,
        param_two=nodes,
        epochs=1, generations=20, keep=0.6, size=20)

In [ ]:
parameters, metrics, performance = go.train()

[ 9. 54.  4. 54.]
True
Model: "model_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_18 (InputLayer)        [(None, 784)]             0         
_________________________________________________________________
dense_83 (Dense)             (None, 54)                42390     
_________________________________________________________________
dense_84 (Dense)             (None, 54)                2970      
_________________________________________________________________
dropout_49 (Dropout)         (None, 54)                0         
_________________________________________________________________
dense_85 (Dense)             (None, 54)                2970      
_________________________________________________________________
dropout_50 (Dropout)         (None, 54)                0         
_________________________________________________________________
dense_86 (Dense)             (None,

10000/10000 [==============================] - 0s 43us/sample - loss: 0.6100 - categorical_accuracy: 0.8194
[ 3. 73.  3. 75.]
True
Model: "model_20"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_21 (InputLayer)        [(None, 784)]             0         
_________________________________________________________________
dense_108 (Dense)            (None, 74)                58090     
_________________________________________________________________
dense_109 (Dense)            (None, 74)                5550      
_________________________________________________________________
dropout_68 (Dropout)         (None, 74)                0         
_________________________________________________________________
dense_110 (Dense)            (None, 74)                5550      
_________________________________________________________________
dropout_69 (Dropout)         (None, 74)                0   

10000/10000 [==============================] - 0s 36us/sample - loss: 1.6852 - categorical_accuracy: 0.3973
[ 1. 13.  3.  5.]
True
Model: "model_24"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_25 (InputLayer)        [(None, 784)]             0         
_________________________________________________________________
dense_132 (Dense)            (None, 9)                 7065      
_________________________________________________________________
dense_133 (Dense)            (None, 9)                 90        
_________________________________________________________________
dropout_84 (Dropout)         (None, 9)                 0         
_________________________________________________________________
dense_134 (Dense)            (None, 9)                 90        
_________________________________________________________________
dropout_85 (Dropout)         (None, 9)                 0   

10000/10000 [==============================] - 0s 34us/sample - loss: 0.5048 - categorical_accuracy: 0.8820
[ 7. 84.  1. 30.]
True
Model: "model_28"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_29 (InputLayer)        [(None, 784)]             0         
_________________________________________________________________
dense_156 (Dense)            (None, 57)                44745     
_________________________________________________________________
dense_157 (Dense)            (None, 57)                3306      
_________________________________________________________________
dropout_100 (Dropout)        (None, 57)                0         
_________________________________________________________________
dense_158 (Dense)            (None, 57)                3306      
_________________________________________________________________
dropout_101 (Dropout)        (None, 57)                0   

10000/10000 [==============================] - 0s 32us/sample - loss: 1.7817 - categorical_accuracy: 0.3666
[ 1. 37.  9. 97.]
True
Model: "model_32"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_33 (InputLayer)        [(None, 784)]             0         
_________________________________________________________________
dense_184 (Dense)            (None, 67)                52595     
_________________________________________________________________
dense_185 (Dense)            (None, 67)                4556      
_________________________________________________________________
dropout_120 (Dropout)        (None, 67)                0         
_________________________________________________________________
dense_186 (Dense)            (None, 67)                4556      
_________________________________________________________________
dropout_121 (Dropout)        (None, 67)                0   

10000/10000 [==============================] - 0s 40us/sample - loss: 0.6401 - categorical_accuracy: 0.8246
[ 8. 90.  3. 10.]
True
Model: "model_35"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_36 (InputLayer)        [(None, 784)]             0         
_________________________________________________________________
dense_209 (Dense)            (None, 50)                39250     
_________________________________________________________________
dense_210 (Dense)            (None, 50)                2550      
_________________________________________________________________
dropout_139 (Dropout)        (None, 50)                0         
_________________________________________________________________
dense_211 (Dense)            (None, 50)                2550      
_________________________________________________________________
dropout_140 (Dropout)        (None, 50)                0   

10000/10000 [==============================] - 0s 39us/sample - loss: 1.1124 - categorical_accuracy: 0.5930
[ 5 78  6 59]
True
Model: "model_39"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_40 (InputLayer)        [(None, 784)]             0         
_________________________________________________________________
dense_238 (Dense)            (None, 68)                53380     
_________________________________________________________________
dense_239 (Dense)            (None, 68)                4692      
_________________________________________________________________
dropout_160 (Dropout)        (None, 68)                0         
_________________________________________________________________
dense_240 (Dense)            (None, 68)                4692      
_________________________________________________________________
dropout_161 (Dropout)        (None, 68)                0       

10000/10000 [==============================] - 2s 155us/sample - loss: 0.1970 - categorical_accuracy: 0.9399
[ 7 15  2  3]
True
Model: "model_43"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_44 (InputLayer)        [(None, 784)]             0         
_________________________________________________________________
dense_263 (Dense)            (None, 9)                 7065      
_________________________________________________________________
dense_264 (Dense)            (None, 9)                 90        
_________________________________________________________________
dropout_177 (Dropout)        (None, 9)                 0         
_________________________________________________________________
dense_265 (Dense)            (None, 9)                 90        
_________________________________________________________________
dropout_178 (Dropout)        (None, 9)                 0      

10000/10000 [==============================] - 0s 40us/sample - loss: 1.2140 - categorical_accuracy: 0.5864
[ 4  7  4 70]
True
Model: "model_47"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_48 (InputLayer)        [(None, 784)]             0         
_________________________________________________________________
dense_288 (Dense)            (None, 38)                29830     
_________________________________________________________________
dense_289 (Dense)            (None, 38)                1482      
_________________________________________________________________
dropout_194 (Dropout)        (None, 38)                0         
_________________________________________________________________
dense_290 (Dense)            (None, 38)                1482      
_________________________________________________________________
dropout_195 (Dropout)        (None, 38)                0       

In [9]:
performance

array([[0.4278    , 0.86580002],
       [0.43979999, 0.84490001]])